output_file: ../Data/test2_output.json
data_file: ../Data/test2_database.db
table_name: person_info

fields:
  - field_name: name
    label: Name
  - field_name: birthday
    label: Birthday [yyyy.hh.dd]
  - field_name: address
    label: Address
  - field_name: height
    label: Height [cm]
